resolver: lts-16.20

packages:
  - 03-testing
  - 04-testing
  - 05-web
  - 06-parsing
  - 07-json
  - 08-game
  - 09-compiler

extra-deps:
  # for Windows
    - regex-posix-clib-2.7

flags:
  regex-posix:
    _regex-posix-clib: true  # for windows

nix:
  pure: false
  packages: [zlib.dev, zlib.out]
