name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ghc_warnings:
    -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns
      -Wredundant-constraints
    -Wwarn=missing-signatures -Wwarn=type-defaults -Wwarn=unused-top-binds
    -Wno-unticked-promoted-constructors
  compile: ghc $ghc_warnings -Werror
  stack: stack --no-terminal --install-ghc
  stack_test: $stack --ghc-options="${ghc_warnings[*]}" --ghc-options=-Werror

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      # with:
      #   ghc-version: '8.8.4'
      #   cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key:
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}
        # -${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # - name: Install stack
    #   run:
    #     - mkdir -p ~/.local/bin
    #     - export PATH=$HOME/.local/bin:$PATH
    #     - |
    #       if which stack; then
    #         stack --version
    #       else
    #         curl -sSL https://get.haskellstack.org/ | sh
    #     - export STACK="stack --no-terminal --install-ghc"

    # - name: Install dependencies
    #   run: stack build --test --only-dependencies
    # - name: Build
    #   run: stack build
    # - name: Run tests
    #   run: stack test

    - {name: Compile task 01, run: $compile 01-intro/*.hs}
    - {name: Compile task 02, run: $compile 02-types/*.hs}
    - {name: Run tests in task 03, run: $stack_test 03-testing}
